# Generated by Django 3.2.9 on 2021-11-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тега')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_news', models.BooleanField(default=False, help_text='Новости будут отображаться на соответствующей странице новостей', verbose_name='Является новостью?')),
                ('title_image', models.ImageField(upload_to='posts/images', verbose_name='Изображение для новости')),
                ('body', models.TextField(verbose_name='Текст новости')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('tags', models.ManyToManyField(blank=True, related_name='Теги', to='blog.PostTag')),
            ],
        ),
    ]
