# Generated by Django 3.2.9 on 2021-11-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211112_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='Превью статьи'),
        ),
    ]
