# Generated by Django 3.2.9 on 2021-11-13 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_posts', to='blog.post')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_posts', to='blog.post')),
            ],
        ),
    ]
